app/Http/routes.php
<?php
use App\Events;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect('/threejs-planete');
});

// test : fire public envent
Route::get('fire', function () {
    // this fires the event
    event(new App\Events\EventName());
    return "public event fired";
});

// test : fire private event
Route::get('fire-private', function () {
    // this fires the event
    event(new App\Events\PrivateMessageTest());
    return "private event fired";
});

Route::get('socket-example', function () {
    // this checks for the event
    return view('socket_example');
});

Route::get('threejs-example', function () {
    return view('threejs-example');
});

Route::get('threejs-planete', function () {
    $events = Events::all();
    $lesEvents = array();
    foreach($events as $key=>$value)
    {
        $lesEvents[] = array(
            "id" => $value->id,
            "name" => $value->name,
            "type" => $value->type,
            "color" => $value->color
            );
    }
    return view('threejs-planete', compact('lesEvents'));
});


Route::get('user-info', function () {
    return view('user.user-info');
});

Route::get('vocal', function () {
    return view('vocal.test');
});

Route::get('read-test', function() {
    return view('read');
});

Route::resource('report', 'ReportController');

Route::get('help', function() {
    return view('help');
});

app/Events.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Events extends Model
{
    protected $table = 'events';
    protected $fillable = ['name', 'type', 'color'];
}

app/Report.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Report extends Model
{
    protected $table = 'report';
    protected $fillable = ['event_type', 'location', 'description'];
}

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

abstract class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Report;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use App\Events;
use Input, Redirect;
use App\Quotation;

class ReportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $reports = Report::all();
      return view('report.index', compact('reports'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $events = Events::orderBy('name')->get();
        return view('report.create', compact('events'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request, [
        'event_type' => 'required',
        'location' => 'required|max:30',
        'description' => 'required|max:200',
      ]);
      Report::create([
        'event_type' => $request->input('event_type'),
        'location' => $request->input('location'),
        'description' => $request->input('description'),
      ]);

      return redirect('report/');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $report = Report::find($id);
      $event = Events::find($report->event_type);
      $type = $event->name;
      return view('report.show', compact('report', 'type'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Panic Map</title>

	<link href="{{ asset('assets/bower/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">

	<!-- Fonts -->
	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
	<link href="{{ asset('assets/css/style.css') }}" rel="stylesheet">

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
	@yield('head')
</head>
<body onload="initialize()">
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
					<span class="sr-only">Toggle Navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{{ url('/home') }}">Panic Map</a>
			</div>

			<div class="collapse navbar-collapse" id="navbar">
				<ul class="nav navbar-nav">
					<!--<li><a href="{{ url('/') }}">Welcome</a></li>
					<li><a href="{{ url('/threejs-example') }}">Three.js example</a></li> -->
					<!--<li><a href="{{ url('/socket-example') }}">Socket.io example</a></li>
					<li><a href="{{ url('/fire') }}" target="_blank">Fire public event</a></li>
					<li><a href="{{ url('/fire-private') }}" target="_blank">Fire private event</a></li>-->
					<li><a href="{{ url('/threejs-planete') }}">Planete</a></li>
					<li><a href="{{ url('/report/') }}">Reports</a></li>
					<li><a href="{{ url('/user-info/') }}">General advice</a></li>
					<li><a href="{{ url('/help/') }}">Help</a></li>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					<li style="display:inline-block;text-align:right;"><a href="#" style="outline:none;"><img src="{{ url('assets/img/zoom_in.png') }}" style="margin-right:20px;cursor:pointer;" width="30" id="zoom_in"><img src="{{ url('assets/img/zoom_out.png') }}" style="cursor:pointer;" width="30" id="zoom_out"></a></li>
					<!--@if(auth()->guest())
						@if(!Request::is('auth/login'))
							<li><a href="{{ url('/auth/login') }}">Login</a></li>
						@endif
						@if(!Request::is('auth/register'))
							<li><a href="{{ url('/auth/register') }}">Register</a></li>
						@endif
					@else
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ auth()->user()->name }} <span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="{{ url('/auth/logout') }}">Logout</a></li>
							</ul>
						</li>
					@endif
					-->
				</ul>

				<!-- Button trigger modal -->
				<a href="{{ url('/report/create') }}">
			    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
			      Publish a report
			    </button>
		    </a>

			</div>
		</div>
	</nav>
	<div id="earth_div"></div>

	@yield('content')

	<!-- Scripts -->
	<script src="{{ asset('assets/bower/jquery/dist/jquery.min.js') }}"></script>
	<script src="{{ asset('assets/bower/bootstrap/dist/js/bootstrap.min.js') }}"></script>
	<script src='https://code.responsivevoice.org/responsivevoice.js'></script>
	<script src="{{ asset('assets/js/scribe.js') }}"></script>
	<script src="{{ asset('assets/js/read-site.js') }}"></script>
	@yield('javascript')
</body>
</html>

resources/views/help.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
	      		<div class="panel-heading">
	       			<h2>Help for adaptative features</h2>
	      		</div>
		      	<div class="panel-body" id="to-read">
		        	<h3>Compatibility<span style="display:none;">.</span></h3>
		        		<p>The Text-to-speech feature is only available on Firefox. Please use it instead of Google Chrome, Opera or Safari.</p>
		        	<h3>Text-to-speech<span style="display:none;">.</span></h3>
		        		<p>To enable the text-to-speech feature, just press the "r" key. Press it again to pause the reading then press it again to resume it. If it is reading too fast, you can restart the reading by a double tap on the "r" key.</p>
		        	<h3>Font size<span style="display:none;">.</span></h3>
		        		<p>If the font is too small for you, you can increase its size by clicking on the magnifying glass with the "plus" sign on the top right of the page. You can also decrease the font size by clicking on the magnifying glass with the "minus" sign on the top right of the page.<br>To be faster, you can press the "plus" key to increase the font size and the "minus" key to decrease it.</p>
		        	<h3>About<span style="display:none;">.</span></h3>
		        		<p>The home page is made with WEBGL which displays a world map in 3d. Alerts are displayed when tweets related to keywords that we defined are posted (exemple : earthquakes).<br>In the report section, you can send a post wich will allow users to add alerts without tweeting (it's not displayed in the world map yet, maybe in a future version :p).<br>Finally, in the "General advice" section, you can find the correct way to react to every dangerous situation that are displayed in our world map.<br>We also have developped views to display summaries of alerts when you click on a alert of the world map (but this view is not displayed yet but the start is here).</p>	
		    	</div>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/home.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Home</div>

				<div class="panel-body">
					You are logged in!<br><br>
					<button id="adaptative_features" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Help for adaptative features</button>
				</div>
			</div>

			<!-- Modal -->
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
			  	<div class="modal-dialog" role="document">
			   		<div class="modal-content">
			      		<div class="modal-header">
			        		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			       			<h4 class="modal-title" id="myModalLabel">Help for adaptative features</h4>
			      		</div>
				      	<div class="modal-body" id="to-read">
				        	<h3>Compatibility<span style="display:none;">.</span></h3>
				        		<p>The Text-to-speech feature is only available on Firefox. Please use it instead of Google Chrome, Opera or Safari.</p>
				        	<h3>Text-to-speech<span style="display:none;">.</span></h3>
				        		<p>To enable the text-to-speech feature, just press the "r" key. Press it again to pause the reading then press it again to resume it. If it is reading too fast, you can restart the reading by a double tap on the "r" key.</p>
				        	<h3>Font size<span style="display:none;">.</span></h3>
				        		<p>If the font is too small for you, you can increase its size by clicking on the magnifying glass with the "plus" sign on the top right of the page. You can also decrease the font size by clicking on the magnifying glass with the "minus" sign on the top right of the page.<br>To be faster, you can press the "plus" key to increase the font size and the "minus" key to decrease it.</p>
				      	</div>
				      	<div class="modal-footer">
				        	<button type="button" id="close-modal" class="btn btn-primary" data-dismiss="modal">Close</button>
				      	</div>
			    	</div>
			  	</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('javascript')
	<script>
		window.addEventListener('load', function () {
			document.getElementById('adaptative_features').addEventListener('click', function () {
				restartReading();
			});

			$('#myModal').on('hidden.bs.modal', function (e) {
			 	stopReading();
			})
		});
	</script>
@stop

resources/views/read.blade.php
@extends('app')

@section('content')
<div class="container" id="to-read">
	<div id="audio"></div>
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel panel-heading">
					TEST Audio
				</div>
				<div class="panel panel-body">
					The F.B.I. is treating the shooting as a potential terrorist act, though they are far from concluding that it was, two law enforcement officials said Thursday. The suspects’ extensive arsenal, their recent Middle East travels and evidence that one had been in touch with people with Islamist extremist views, both in the United States and abroad, all contributed to the decision to refocus the investigation. But officials emphasized that they were unclear what set off the attack, and said they were not ready to call it terrorism.
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/report/create.blade.php
@extends('app')

@section('content')
<div class="container">
  <div class="row">
    <form role="form" class="col-md-6" method="post" action="{{route('report.store')}}">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="form-group">
            <label for="event_type">Event type</label>
            <select name="event_type" required>
              @foreach ($events as $event)
                <option value="{{ $event->id }}">{{ $event->name }}</option> 
              @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="location">Location</label>
            <input type="text" class="form-control" name="location" required>
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <input type="text" class="form-control" name="description" required>
        </div>

        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <button type="submit" class="btn btn-default">Post this report</button>
    </form>
  </div>
</div>
@endsection

resources/views/report/index.blade.php
@extends('app')

@section('content')
    <h2>Reports</h2>

    @if ( !$reports->count() )
        <p>There are no report.</p>
    @else
        <ul>
            @foreach($reports as $report)
                <li>
                    <a href="{{ url('report/' . $report->id) }}">{{ $report->location }}</a>
                </li>
            @endforeach
        </ul>
    @endif

@endsection

resources/views/report/show.blade.php
@extends('app')

@section('content')

<div class="container">
	<div class="row">
		<h2>{{ $type }} in  {{ $report->location }} </h2>
		<p> {{ $report->description }} </p>
		<p> First report at {{$report->created_at}} </p>
		<?php 
			$template = 'user.info-' . strtolower($type);
			$template2 = 'twitterFeeds.twitter-' . strtolower($type) . 's';
		?>
		@include($template)
		@include($template2)
  </div>
</div>

@endsection

resources/views/socket_example.blade.php
@extends('app')

@section('content')
    <p id="power">0</p>
    <ul id="chat">
    </ul>
@stop

@section('javascript')
    <!--<script src="https://cdn.socket.io/socket.io-1.3.5.js"></script>-->
    <script src="{{ asset('assets/js/socket.io/socket.io.js') }}"></script>
    <script>
        var socket = io("{{url()}}:3000");
        
        socket.on("test-channel:App\\Events\\EventName", function(message){
            // increase the power everytime we load test route
            $('#power').text(parseInt($('#power').text()) + parseInt(message.data.power));
        });

        socket.on("test-private-message:App\\Events\\PrivateMessageTest", function(message){
            $('#chat').append('<li>'+message.from.name+' : '+message.text+'</li>');
        });
    </script>
@stop

resources/views/threejs-example.blade.php
@extends('app')

@section('content')
    <style>
        body {
            font-family: Monospace;
            background-color: #000;
            margin: 0px;
            overflow: hidden;
        }
    </style>
@stop

@section('javascript')
    <script src="{{ asset('assets/bower/three.js/build/three.min.js') }}"></script>
    <script src="{{ asset('assets/js/Detector.js') }}"></script>
    <script src="{{ asset('assets/js/stats.min.js') }}"></script>
    <script>
        var imgPath = "{{ asset('assets/img/UV_Grid_Sm.jpg') }}";
    </script>
    <script src="{{ asset('assets/js/threejs-example.js') }}"></script>
@stop

resources/views/threejs-planete.blade.php
@extends('app')

@section('content')
    <style>
        body {
            font-family: Monospace;
            background-color: #000;
            margin: 0px;
            overflow: hidden;
            
        }
    </style>
@stop

@section('javascript')
    <script src="{{ asset('assets/bower/three.js/build/three.min.js') }}"></script>
    <script src="{{ asset('assets/js/Detector.js') }}"></script>
    <script src="{{ asset('assets/js/stats.min.js') }}"></script>
    <script>
        var imgPath = "{{ asset('assets/img/UV_Grid_Sm.jpg') }}";
        // transformation en tableau JSON des types d'événement
        var eventsInterm = "{{ json_encode($lesEvents) }}";
        var intermEvents = eventsInterm.replace(/&quot;/g, '"');
        var typesEvents = jQuery.parseJSON(intermEvents);
        console.log(typesEvents);
    </script>
    <!-- api webglearth pour le globe -->
    <script src="{{ asset('assets/js/webglearth_api.js') }}"></script>
    <!-- les options pour l'api -->
    <script src="{{ asset('assets/js/threejs-planete.js') }}"></script>
    <script src="{{ asset('assets/js/socket.io/socket.io.js') }}"></script>
    <script>
        var socket = io("{{url()}}:3210");
        var imark = 1;
        var afermer;
        socket.on("tweet", function(tweet, type){
            console.log("message");

            var color;
            for (var j=0; j<typesEvents.length;j++) {
                if(type == typesEvents[j].name) {
                    color = typesEvents[j].color;
                }
            }

            var x = tweet.place.bounding_box.coordinates[0][0][1];
            var y = tweet.place.bounding_box.coordinates[0][0][0];
            
            var marker = WE.marker([x, y], color).addTo(earth);
            marker.bindPopup("<b>" + type + "</b><br>" + tweet.place.name, {maxWidth: 150, closeButton: true});  
            //allMarkers.push(marker);
            marker.id = imark;
            var enregistrerIdMarker = function(e) {
                if(afermer) { // not null = existe, donc y'a une valeur à fermer
                    afermer.closePopup();
                    afermer=marker;
                }
                else { // afermer = 1ère popup qu'on ouvre
                    afermer=marker;
                }
                
            };
            marker.on('click', enregistrerIdMarker);
            imark++;

            /*allEvents.push({ 
                x:tweet.place.bounding_box.coordinates[0][0][1], 
                y:tweet.place.bounding_box.coordinates[0][0][0], 
                type: type, 
                ville: tweet.place.name
            });
            */
        });
    </script>
@stop

resources/views/twitterFeeds/twitter-attacks.blade.php
<a class="twitter-timeline" href="https://twitter.com/search?q=%23attacks%20%23terrorist" data-widget-id="672577753896603648">Tweets sur #attacks #terrorist</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

resources/views/twitterFeeds/twitter-avalanches.blade.php
<a class="twitter-timeline" href="https://twitter.com/hashtag/avalanche" data-widget-id="672576913957904384">Tweets sur #avalanche</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

resources/views/twitterFeeds/twitter-earthquakes.blade.php
<a class="twitter-timeline" href="https://twitter.com/hashtag/earthquakes" data-widget-id="672576184409063428">Tweets sur #earthquakes</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

resources/views/twitterFeeds/twitter-floods.blade.php
<a class="twitter-timeline" href="https://twitter.com/hashtag/flood" data-widget-id="672576675150999552">Tweets sur #flood</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

resources/views/twitterFeeds/twitter-hostage-takings.blade.php
<a class="twitter-timeline" href="https://twitter.com/hashtag/hostages" data-widget-id="672577965381853184">Tweets sur #hostages</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

resources/views/twitterFeeds/twitter-plant-explosions.blade.php
<a class="twitter-timeline" href="https://twitter.com/search?q=%23explosion%20%23plant" data-widget-id="672577308612538368">Tweets sur #explosion #plant</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

resources/views/twitterFeeds/twitter-pollutions.blade.php
<a class="twitter-timeline" href="https://twitter.com/search?q=%23pollution%20%23alert" data-widget-id="672577542356918272">Tweets sur #pollution #alert</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

resources/views/twitterFeeds/twitter-storms.blade.php
<a class="twitter-timeline" href="https://twitter.com/hashtag/storm" data-widget-id="672576512378470401">Tweets sur #storm</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

resources/views/twitterFeeds/twitter-tsunamis.blade.php
<a class="twitter-timeline" href="https://twitter.com/hashtag/tsunami" data-widget-id="672576367519776769">Tweets sur #tsunami</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

resources/views/twitterFeeds/twitter-volcanic-eruptions.blade.php
<a class="twitter-timeline" href="https://twitter.com/hashtag/eruption" data-widget-id="672577103188123649">Tweets sur #eruption</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

resources/views/user/info-attack.blade.php
<div id="to-read">
	<h3>React in case of an terrorist attack<span style="display:none;">.</span></h3>
<div class="panel-group" id="accordion9" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo9">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion9" href="#collapseTwo9" aria-expanded="false" aria-controls="collapseTwo9">
          During a terrorist attack<span style="display:none;">.</span>
        </a>
      </h4>
    </div>
    <div id="collapseTwo9" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingTwo9">
      <div class="panel-body">
        - Try to hide or to find a safety place<span style="display:none;">.</span><br>
        - If you can, try to contact authorities as sneaky as possible<span style="display:none;">.</span><br>
        - If terrorists are not far from you, try to play dead<span style="display:none;">.</span>
      </div>
    </div>
  </div>
</div>
</div>

resources/views/vocal/test.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Home</div>

				<div class="panel-body">
				fgdfg
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

@section('javascript')
    <script src="{{ asset('assets/bower/annyang/annyang.js') }}"></script>
    <script>

    </script>
		<script src="{{ asset('assets/js/scribe.js') }}"></script>
    <script src="{{ asset('assets/js/vocal.js') }}"></script>
@stop